#!/bin/sh

for source in .bundle .gemrc .hushlogin .powconfig .vim .vimrc .zshrc; do
  target=~/`basename $source`
  source=~/.dotfiles/$source

  rm -rf $target
  ln -s $source $target
done

touch ~/.z
