#!/bin/sh

for source in .config/fish .gemrc .gitconfig .hushlogin .vim .vimrc .zshrc; do
  target=~/$source
  source=~/.dotfiles/$source

  rm -rf $target
  ln -sf $source $target
done

touch ~/.z

if [ `whoami` != 'Dominik' ]; then
  echo '.gitconfig: Remember to change your user info'
fi
