#!/bin/sh

for source in .gemrc .gitconfig .hushlogin .vim .vimrc .zshrc; do
  target=~/`basename $source`
  source=~/.dotfiles/$source

  rm -rf $target
  ln -s $source $target
done

touch ~/.z

if [ `whoami` != "Dominik" ]; then
  echo ".gitconfig: Remember to change your user info"
fi
