set -x fish_color_autosuggestion "brblack"
set -x fish_color_command "green"
set -x fish_color_comment "brblack"
set -x fish_color_cwd "blue"
set -x fish_color_cwd_root "red"
set -x fish_color_end "brblack"
set -x fish_color_error "red"
set -x fish_color_escape "brblack"
set -x fish_color_history_current "--bold"
set -x fish_color_host "magenta"
set -x fish_color_match "--background=brblack"
set -x fish_color_normal "normal"
set -x fish_color_operator "cyan"
set -x fish_color_param "normal"
set -x fish_color_quote "yellow"
set -x fish_color_redirection "blue"
set -x fish_color_search_match "--background=brblack"
set -x fish_color_selection "black" "--background=white"
set -x fish_color_user "magenta"
set -x fish_color_valid_path "--underline"

set -x fish_pager_color_completion "normal"
set -x fish_pager_color_description "normal"
set -x fish_pager_color_prefix "--underline"
set -x fish_pager_color_progress "brblack"
